// try {
//     let p = 10
//     console.log(p)
// } catch (error) {
//     console.log("This is an error")
// }
// finally{
//     console.log("I am a good boy")
// }

try {
    console.log(a)
} catch (error) {
    console.log("This is an error")
}
finally{
    console.log("I am a good boy")
    //Close the file
    //Exit the loop
    //Write to the log file
}